### PR TITLE
Collapse conditionals

### PR DESCRIPTION
**Pull request by don-smith**
This doesn't fix any bugs or add any features ... just a small refactoring. 

The `.python-version` file is nice when Python 3.x is active because the `node-gyp` part of `npm i` will fail if it can't find `python2`.

If the code is undergoing significant churn at the moment and you only want to accept certain kinds of PRs, just let me know.

### CODE REVIEW

**Comment by ahdinosaur** [comment]
nah i'm happy to receive pull requests.

keen for the `.python-version` file. :+1: 

not sure about collapsing the conditionals. the reason i separated them was to maintain the pattern of having `require` calls at the top of the file, although i can see i didn't quite make that happen right. i'll merge but interested in your thoughts on this.

also interested in your thoughts on ES5 `require` vs ES6 `import` in this stack. after using `import` in a few projects, i've become personally disinterested in it, but after experiencing pain in using modules that rely heavily on ES6 (which all our dependencies here do) modules (especially regarding defaults), and developers who use ES6 usually failing to provide ES5 documentation, i could be convinced to use `import` in this stack. `import` enforces static analyze-ability, so to do it "properly" we'd need to do the conditional imports another way (i think it's possible to tell browserify to return empty for dev modules).

**Comment by don-smith** [comment]
Ah, that makes total sense now that you point it out. If I would have noticed that's what you were doing, I might have just moved the first condition up a few lines under the other `require`s. Like you, I also prefer all of the `require`s being at the top of the module/file. In this case, having 2 of the same conditionals felt strange. Hmm, interesting ... I'm of 2 minds on this one.

Since I've moved to ES6, I've only been using `import` and have been pretty happy with it. My preference would be to use `import` in this stack because over time, once everyone is only using ES6, which is already true for many of us, `require` won't be consistent with our other codebases. Once a decision has been made, especially difficult ones like language specifications, I don't tend to hang on to legacy syntax. It sometimes creates unhelpful friction and unnecessary cognitive load for others. Of course your points are valid - it's just about weighing the pros/cons.

I need to look into this further, but it looks like we might be able to load modules conditionally with the [module loader api](http://www.2ality.com/2014/09/es6-modules-final.html#the_ecmascript_6_module_loader_api). Maybe this is what browserify uses - I haven't looked into it yet. I suspect this would satisfy the static code analysers.

The only other [minor] thing that would be good to do eventually is refactor out the `'development'` strings (as used in `if (process.env.NODE_ENV === 'development')`) into something like `if (process.env.NODE_ENV === config.env.development)`. We'll get to it :)

**Comment by ahdinosaur** [comment]
> My preference would be to use `import` in this stack because over time, once everyone is only using ES6, which is already true for many of us, `require` won't be consistent with our other codebases.

cool, `import`.

> I need to look into this further, but it looks like we might be able to load modules conditionally with the module loader api. Maybe this is what browserify uses - I haven't looked into it yet. I suspect this would satisfy the static code analysers.

[browserify](https://github.com/substack/browserify-handbook) aims to provide the same api as [what node modules provide](https://nodejs.org/docs/latest/api/modules.html), so it [works by parsing the AST for `require` calls](https://github.com/substack/browserify-handbook#how-browserify-works).

> `if (process.env.NODE_ENV === config.env.development)`

hmm, we'd to statically input the `config` object, similar to [envify](https://www.npmjs.com/package/envify) does for `process.env`, so those lines will be removed by [uglifyify](https://github.com/hughsk/uglifyify).

**Comment by don-smith** [comment]
Ah, I didn't understand how evnify worked and how uglify optimised the bundle so nicely until following the links you provided. Hmm. I love the production optimisation, but I don't like the idea of maintaining a lot of repeated magic strings. I can already see me chasing down a bug related to me spelling it `devlopment` :) I'd be interested in exploring this more in the future, but I can live with the strings for now since there are obviously more pressing tasks.

**Pull request merged**
